export const Action_Type = {
   ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  CLEAR_CART:"CLEAR_CART",
  UPDATE_CART_ITEM:"UPDATE_CART_ITEM"
}