export const Action_Type = {
  GET_REQUEST:"GET_REQUEST",
  GET_SUCCESS:"GET_SUCCESS",
  GET_FAILURE:"GET_FAILURE",
  GET_REQUEST_BY_ID:"GET_REQUEST_BY_ID",
  GET_SUCCESS_BY_ID:"GET_SUCCESS_BY_ID",
  GET_FAILURE_BY_ID:"GET_FAILURE_BY_ID",
  UPDATE_PRODUCT_STOCK:"UPDATE_PRODUCT_STOCK",
}